name: Update public files
on:
  repository_dispatch:
    types: [update-files]
jobs:
  update-public-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 5sounds-client repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.CLIENT_REPO }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: client

      - name: Install dependencies and build
        run: |
          cd client
          cat package.json
          npm install
          npm run build

      - name: Copy dist files to temporary directory
        run: |
          mkdir temp
          cp -r client/dist/* temp/

      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Copy files to /public
        run: |
          cp -r ../temp/* public/

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          commit-message: Update public files
          title: 'Update public files'
          body: 'This PR updates the public files with the latest dist files.'
          branch: 'update-public-files'
