name: Update public files
on:
  repository_dispatch:
    types: [update-files]

jobs:
  update-public-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: check
        run: |
          ls
          echo "cd .."
          cd ..
          ls
          echo "cd .."
          cd ..
          ls
      - name: Checkout 5sounds-client repo
        uses: actions/checkout@v2
      - name: check
        run: |
          ls
          echo "cd .."
          cd ..
          ls
          echo "cd .."
          cd ..
          ls
